### ISSUE TITLE
[question] Why bidi stream has 1:1 mapping when the spec states otherwise ? 

### ISSUE THREAD

**Issue by bobymicroby** [xiaodongw/grpc-rx#1]
Hello @xiaodongw ,

First let me congratulate you for starting writing the RX stubs I have long intended to, but never
had the time ! I was browsing at the code and something caught my eye .

As stated in [BidiStreamingProcessor](https://github.com/xiaodongw/grpc-rx/blob/master/grpc-rx-stub/src/main/java/io/grpc/rx/core/BidiStreamingProcessor.java#L8) , there is 1:1 mapping between the request and response. But in the specification is stated  :

> A bidirectional streaming RPC where both sides send a sequence of messages using a read-write stream. The two streams operate independently, so clients and servers can read and write in whatever order they like: for example, the server could wait to receive all the client messages before writing its responses, or it could alternately read a message then write a message, or some other combination of reads and writes. The order of messages in each stream is preserved.

Can you shed some light why ?

Cheers, B.

**Comment by xiaodongw** [comment]
Hi @bobymicroby, 

Glad you see my work, this RX stub is still in a very rough stage, I haven't figured out how to map a arbitrary bidi streaming RPC call to a processor interface but keeping a simple way to do flow control.

So, the current BidiStreamingProcessor only supports 1:1 request/response, I may add another process for arbitrary bidi streaming support later.

**Comment by xiaodongw** [comment]
The interface is totally refactored, it is not an issue now, close.

**Comment by vyshane** [comment]
@xiaodongw can you provide more details on the refactoring that makes this issue redundant? Can you post a link to the change so that I can follow along?

**Comment by xiaodongw** [comment]
@vyshane This is the change https://github.com/xiaodongw/grpc-rx/commit/dac090c0303e8014dcbd794dd78f17559e02aef2. 

The new interface is based on RxJava's Single & Flowable, so I think you can use functions like Flowable.scan(), groupBy() to deal with non 1:1 mapped requests/responses.

**Comment by vyshane** [comment]
Thanks @xiaodongw, much appreciated
